@php($type = $type ?? 'project')

@if ($type === 'project')
    <section class="page-section page-section--intro">
        <div class="container content-grid content-grid--split">
            <div class="page-section__header">
                <span class="section-marker"><span class="locale-copy locale-copy--ru">О проекте</span><span class="locale-copy locale-copy--ro">Despre proiect</span><span class="locale-copy locale-copy--en">The project</span></span>
                <h1><span class="locale-copy locale-copy--ru">Практическая поддержка для тех, кто работает с энергией.</span><span class="locale-copy locale-copy--ro">Suport practic pentru cei care lucrează cu energia.</span><span class="locale-copy locale-copy--en">Practical support for people working with energy.</span></h1>
            </div>
            <div class="body-copy page-section__copy">
                <p><span class="locale-copy locale-copy--ru">Green Energy Hub — центр экспертизы, практического обучения и консультационной поддержки в сфере энергоэффективности и возобновляемой энергетики.</span><span class="locale-copy locale-copy--ro">Green Energy Hub este un centru de expertiză, instruire practică și suport consultativ în domeniul eficienței energetice și al energiei regenerabile.</span><span class="locale-copy locale-copy--en">Green Energy Hub is a centre of expertise, practical learning and consultation in energy efficiency and renewable energy.</span></p>
                <p><span class="locale-copy locale-copy--ru">Хаб помогает бизнесу, специалистам и организациям понимать энергопотребление, находить потери и внедрять обоснованные решения.</span><span class="locale-copy locale-copy--ro">Hubul ajută companiile, specialiștii și organizațiile să înțeleagă consumul, să găsească pierderile și să implementeze soluții argumentate.</span><span class="locale-copy locale-copy--en">The Hub helps businesses, specialists and organisations understand energy use, find losses and implement informed solutions.</span></p>
            </div>
        </div>
    </section>
@elseif ($type === 'mission')
    <section class="page-section page-section--intro">
        <div class="container">
            <div class="page-section__header page-section__header--row">
                <div><span class="section-marker"><span class="locale-copy locale-copy--ru">Миссия и цели</span><span class="locale-copy locale-copy--ro">Misiune și obiective</span><span class="locale-copy locale-copy--en">Mission and goals</span></span><h1><span class="locale-copy locale-copy--ru">Сделать энергоэффективность понятной и применимой.</span><span class="locale-copy locale-copy--ro">Facem eficiența energetică clară și aplicabilă.</span><span class="locale-copy locale-copy--en">Making energy efficiency clear and applicable.</span></h1></div>
                <p class="section-head__copy"><span class="locale-copy locale-copy--ru">Даём бизнесу и специалистам доступ к знаниям, экспертизе и практическим решениям.</span><span class="locale-copy locale-copy--ro">Oferim companiilor și specialiștilor acces la cunoștințe, expertiză și soluții practice.</span><span class="locale-copy locale-copy--en">We give businesses and specialists access to knowledge, expertise and practical solutions.</span></p>
            </div>
            <div class="info-grid info-grid--three">
                <article class="info-card info-card--lime"><span class="info-card__number">01</span><h3><span class="locale-copy locale-copy--ru">Доступность</span><span class="locale-copy locale-copy--ro">Accesibilitate</span><span class="locale-copy locale-copy--en">Access</span></h3><p><span class="locale-copy locale-copy--ru">Открываем практические знания для организаций региона.</span><span class="locale-copy locale-copy--ro">Facem cunoștințele practice accesibile organizațiilor din regiune.</span><span class="locale-copy locale-copy--en">Make practical knowledge available to regional organisations.</span></p></article>
                <article class="info-card"><span class="info-card__number">02</span><h3><span class="locale-copy locale-copy--ru">Понимание</span><span class="locale-copy locale-copy--ro">Înțelegere</span><span class="locale-copy locale-copy--en">Understanding</span></h3><p><span class="locale-copy locale-copy--ru">Помогаем увидеть потребление, потери и точки роста.</span><span class="locale-copy locale-copy--ro">Ajutăm la înțelegerea consumului, pierderilor și oportunităților.</span><span class="locale-copy locale-copy--en">Help identify consumption, losses and opportunities.</span></p></article>
                <article class="info-card"><span class="info-card__number">03</span><h3><span class="locale-copy locale-copy--ru">Устойчивость</span><span class="locale-copy locale-copy--ro">Reziliență</span><span class="locale-copy locale-copy--en">Resilience</span></h3><p><span class="locale-copy locale-copy--ru">Укрепляем конкурентоспособность предприятий через экспертизу.</span><span class="locale-copy locale-copy--ro">Consolidăm competitivitatea întreprinderilor prin expertiză.</span><span class="locale-copy locale-copy--en">Strengthen business competitiveness through expertise.</span></p></article>
            </div>
        </div>
    </section>
@elseif ($type === 'directions')
    <section class="page-section page-section--intro page-section--tint">
        <div class="container">
            <div class="page-section__header page-section__header--row">
                <div><span class="section-marker"><span class="locale-copy locale-copy--ru">Направления работы</span><span class="locale-copy locale-copy--ro">Direcții de lucru</span><span class="locale-copy locale-copy--en">What we do</span></span><h1><span class="locale-copy locale-copy--ru">От консультации до внедрения.</span><span class="locale-copy locale-copy--ro">De la consultanță la implementare.</span><span class="locale-copy locale-copy--en">From consultation to implementation.</span></h1></div>
                <p class="section-head__copy"><span class="locale-copy locale-copy--ru">Выберите формат поддержки, который отвечает вашей задаче.</span><span class="locale-copy locale-copy--ro">Alegeți formatul de suport potrivit obiectivului dumneavoastră.</span><span class="locale-copy locale-copy--en">Choose the support format that fits your task.</span></p>
            </div>
            <div class="info-grid info-grid--three">
                <article class="info-card"><span class="info-card__number">01</span><h3><span class="locale-copy locale-copy--ru">Консультационная поддержка</span><span class="locale-copy locale-copy--ro">Suport consultativ</span><span class="locale-copy locale-copy--en">Consultation support</span></h3><p><span class="locale-copy locale-copy--ru">Разбираем вопросы энергопотребления и возможных мер.</span><span class="locale-copy locale-copy--ro">Analizăm consumul și măsurile posibile.</span><span class="locale-copy locale-copy--en">Make sense of energy use and possible measures.</span></p></article>
                <article class="info-card"><span class="info-card__number">02</span><h3><span class="locale-copy locale-copy--ru">Энергетические обследования</span><span class="locale-copy locale-copy--ro">Evaluări energetice</span><span class="locale-copy locale-copy--en">Energy assessments</span></h3><p><span class="locale-copy locale-copy--ru">Изучаем объект, оборудование, процессы и потери.</span><span class="locale-copy locale-copy--ro">Studiem obiectul, echipamentele, procesele și pierderile.</span><span class="locale-copy locale-copy--en">Study the site, equipment, processes and losses.</span></p></article>
                <article class="info-card"><span class="info-card__number">03</span><h3><span class="locale-copy locale-copy--ru">Обучение специалистов</span><span class="locale-copy locale-copy--ro">Instruirea specialiștilor</span><span class="locale-copy locale-copy--en">Specialist training</span></h3><p><span class="locale-copy locale-copy--ru">Соединяем теорию с практикой на реальных задачах.</span><span class="locale-copy locale-copy--ro">Conectăm teoria cu practica pe sarcini reale.</span><span class="locale-copy locale-copy--en">Connect theory with hands-on work on real tasks.</span></p></article>
                <article class="info-card"><span class="info-card__number">04</span><h3><span class="locale-copy locale-copy--ru">Оборудование</span><span class="locale-copy locale-copy--ro">Echipamente</span><span class="locale-copy locale-copy--en">Equipment</span></h3><p><span class="locale-copy locale-copy--ru">Практика работы с измерительными и демонстрационными приборами.</span><span class="locale-copy locale-copy--ro">Lucru practic cu echipamente de măsurare și demonstrație.</span><span class="locale-copy locale-copy--en">Hands-on work with measurement and demonstration equipment.</span></p></article>
                <article class="info-card"><span class="info-card__number">05</span><h3><span class="locale-copy locale-copy--ru">База знаний</span><span class="locale-copy locale-copy--ro">Bază de cunoștințe</span><span class="locale-copy locale-copy--en">Knowledge base</span></h3><p><span class="locale-copy locale-copy--ru">Материалы, отчёты и обезличенные рекомендации.</span><span class="locale-copy locale-copy--ro">Materiale, rapoarte și recomandări anonimizate.</span><span class="locale-copy locale-copy--en">Materials, reports and anonymised recommendations.</span></p></article>
                <article class="info-card"><span class="info-card__number">06</span><h3><span class="locale-copy locale-copy--ru">Профессиональное сотрудничество</span><span class="locale-copy locale-copy--ro">Colaborare profesională</span><span class="locale-copy locale-copy--en">Professional collaboration</span></h3><p><span class="locale-copy locale-copy--ru">Обмен опытом между бизнесом, экспертами и организациями.</span><span class="locale-copy locale-copy--ro">Schimb de experiență între companii, experți și organizații.</span><span class="locale-copy locale-copy--en">Exchange between businesses, experts and organisations.</span></p></article>
            </div>
        </div>
    </section>
@elseif ($type === 'audits')
    <section class="page-section page-section--intro">
        <div class="container">
            <div class="page-section__header page-section__header--row"><div><span class="section-marker"><span class="locale-copy locale-copy--ru">Энергоаудиты</span><span class="locale-copy locale-copy--ro">Audituri energetice</span><span class="locale-copy locale-copy--en">Energy assessments</span></span><h1><span class="locale-copy locale-copy--ru">Измерить, понять, найти потери.</span><span class="locale-copy locale-copy--ro">Măsurați, înțelegeți, găsiți pierderile.</span><span class="locale-copy locale-copy--en">Measure, understand and find losses.</span></h1></div><p class="section-head__copy"><span class="locale-copy locale-copy--ru">Энергетическое обследование переводит предположения в рекомендации, основанные на данных.</span><span class="locale-copy locale-copy--ro">Evaluarea energetică transformă presupunerile în recomandări bazate pe date.</span><span class="locale-copy locale-copy--en">An energy assessment turns assumptions into data-based recommendations.</span></p></div>
            <ol class="step-list"><li><span class="step-list__number">01</span><div><h3><span class="locale-copy locale-copy--ru">Собрать информацию</span><span class="locale-copy locale-copy--ro">Colectăm informații</span><span class="locale-copy locale-copy--en">Gather information</span></h3><p><span class="locale-copy locale-copy--ru">Счета, режимы, оборудование и исходные документы.</span><span class="locale-copy locale-copy--ro">Facturi, regimuri, echipamente și documente inițiale.</span><span class="locale-copy locale-copy--en">Bills, operating modes, equipment and initial documents.</span></p></div></li><li><span class="step-list__number">02</span><div><h3><span class="locale-copy locale-copy--ru">Осмотреть и измерить</span><span class="locale-copy locale-copy--ro">Inspectăm și măsurăm</span><span class="locale-copy locale-copy--en">Inspect and measure</span></h3><p><span class="locale-copy locale-copy--ru">Проверяем объект и используем измерительное оборудование.</span><span class="locale-copy locale-copy--ro">Verificăm obiectul și folosim echipamente de măsurare.</span><span class="locale-copy locale-copy--en">Inspect the site and use measurement equipment.</span></p></div></li><li><span class="step-list__number">03</span><div><h3><span class="locale-copy locale-copy--ru">Подготовить рекомендации</span><span class="locale-copy locale-copy--ro">Pregătim recomandări</span><span class="locale-copy locale-copy--en">Prepare recommendations</span></h3><p><span class="locale-copy locale-copy--ru">Формируем выводы, приоритеты и ожидаемый эффект.</span><span class="locale-copy locale-copy--ro">Formulăm concluzii, priorități și efectul estimat.</span><span class="locale-copy locale-copy--en">Set out findings, priorities and expected impact.</span></p></div></li></ol>
        </div>
    </section>
    <section class="page-section page-section--tint"><div class="container content-grid content-grid--image"><div class="page-image-card">@include('partials.responsive-image', ['name' => 'infrastructure-beta', 'alt' => '', 'loading' => 'lazy'])<span class="page-image-card__label"><span class="locale-copy locale-copy--ru">Практика измерений</span><span class="locale-copy locale-copy--ro">Măsurători practice</span><span class="locale-copy locale-copy--en">Practical measurement</span></span></div><div><span class="section-marker"><span class="locale-copy locale-copy--ru">Публикации</span><span class="locale-copy locale-copy--ro">Publicații</span><span class="locale-copy locale-copy--en">Publications</span></span><h2><span class="locale-copy locale-copy--ru">Обезличенные обследования будут доступны в базе.</span><span class="locale-copy locale-copy--ro">Evaluările anonimizate vor fi disponibile în bază.</span><span class="locale-copy locale-copy--en">Anonymised assessments will be available in the database.</span></h2><a class="button" href="{{ route('about.reports') }}"><span class="locale-copy locale-copy--ru">Смотреть отчёты</span><span class="locale-copy locale-copy--ro">Vezi rapoartele</span><span class="locale-copy locale-copy--en">View reports</span><span aria-hidden="true">→</span></a></div></div></section>
@elseif ($type === 'results')
    <section class="page-section page-section--intro page-section--tint"><div class="container"><div class="page-section__header page-section__header--row"><div><span class="section-marker"><span class="locale-copy locale-copy--ru">Результаты проекта</span><span class="locale-copy locale-copy--ro">Rezultatele proiectului</span><span class="locale-copy locale-copy--en">Project results</span></span><h1><span class="locale-copy locale-copy--ru">Только фактические результаты.</span><span class="locale-copy locale-copy--ro">Doar rezultate reale.</span><span class="locale-copy locale-copy--en">Actual results only.</span></h1></div><p class="section-head__copy"><span class="locale-copy locale-copy--ru">Показатели Green Energy Hub будут обновляться по мере появления подтверждённых данных.</span><span class="locale-copy locale-copy--ro">Indicatorii Green Energy Hub vor fi actualizați pe măsură ce apar date confirmate.</span><span class="locale-copy locale-copy--en">Green Energy Hub metrics will be updated as confirmed data becomes available.</span></p></div><div class="metric-grid"><article class="metric-card"><strong>[—]</strong><span><span class="locale-copy locale-copy--ru">проведённых обследований</span><span class="locale-copy locale-copy--ro">evaluări realizate</span><span class="locale-copy locale-copy--en">assessments completed</span></span></article><article class="metric-card metric-card--soft"><strong>[—]</strong><span><span class="locale-copy locale-copy--ru">предприятий с рекомендациями</span><span class="locale-copy locale-copy--ro">întreprinderi cu recomandări</span><span class="locale-copy locale-copy--en">businesses with recommendations</span></span></article><article class="metric-card"><strong>[—]</strong><span><span class="locale-copy locale-copy--ru">подготовленных специалистов</span><span class="locale-copy locale-copy--ro">specialiști instruiți</span><span class="locale-copy locale-copy--en">specialists trained</span></span></article><article class="metric-card metric-card--soft"><strong>[—]</strong><span><span class="locale-copy locale-copy--ru">практических материалов</span><span class="locale-copy locale-copy--ro">materiale practice</span><span class="locale-copy locale-copy--en">practical materials</span></span></article></div></div></section>
@elseif ($type === 'reports')
    <section class="page-section page-section--intro"><div class="container"><div class="page-section__header page-section__header--row"><div><span class="section-marker"><span class="locale-copy locale-copy--ru">Отчёты</span><span class="locale-copy locale-copy--ro">Rapoarte</span><span class="locale-copy locale-copy--en">Reports</span></span><h1><span class="locale-copy locale-copy--ru">Открытые материалы и выводы.</span><span class="locale-copy locale-copy--ro">Materiale și concluzii publice.</span><span class="locale-copy locale-copy--en">Public materials and findings.</span></h1></div><p class="section-head__copy"><span class="locale-copy locale-copy--ru">Отчёты, аналитические документы и обезличенные рекомендации проекта.</span><span class="locale-copy locale-copy--ro">Rapoarte, documente analitice și recomandări anonimizate ale proiectului.</span><span class="locale-copy locale-copy--en">Project reports, analytical documents and anonymised recommendations.</span></p></div><div class="placeholder-grid"><article class="content-card"><span class="content-card__meta">REPORT · [дата]</span><h3><span class="locale-copy locale-copy--ru">Отчёт по энергетическому обследованию [объект]</span><span class="locale-copy locale-copy--ro">Raport de evaluare energetică [obiect]</span><span class="locale-copy locale-copy--en">Energy assessment report [site]</span></h3><p><span class="locale-copy locale-copy--ru">Описание, период, язык и файл будут добавлены из базы.</span><span class="locale-copy locale-copy--ro">Descrierea, perioada, limba și fișierul vor fi adăugate din bază.</span><span class="locale-copy locale-copy--en">Description, period, language and file will be added from the database.</span></p><a class="card-link" href="#"><span class="locale-copy locale-copy--ru">Открыть документ</span><span class="locale-copy locale-copy--ro">Deschideți documentul</span><span class="locale-copy locale-copy--en">Open document</span><span aria-hidden="true">↗</span></a></article><article class="content-card"><span class="content-card__meta">ANALYSIS · [период]</span><h3><span class="locale-copy locale-copy--ru">Практические предложения [тема]</span><span class="locale-copy locale-copy--ro">Propuneri practice [temă]</span><span class="locale-copy locale-copy--en">Practical proposals [topic]</span></h3><p><span class="locale-copy locale-copy--ru">Обезличенные выводы и рекомендации для дальнейшего применения.</span><span class="locale-copy locale-copy--ro">Concluzii și recomandări anonimizate pentru aplicare.</span><span class="locale-copy locale-copy--en">Anonymised findings and recommendations for future use.</span></p><a class="card-link" href="#"><span class="locale-copy locale-copy--ru">Открыть документ</span><span class="locale-copy locale-copy--ro">Deschideți documentul</span><span class="locale-copy locale-copy--en">Open document</span><span aria-hidden="true">↗</span></a></article></div></div></section>
@endif
