@extends('layouts.site')
@section('content')
<section class="page-section page-section--intro">
    <div class="container">
        <div class="page-section__header page-section__header--row">
            <div><span class="section-marker"><span class="locale-copy locale-copy--ru">Лента возможностей</span><span class="locale-copy locale-copy--ro">Fluxul oportunităților</span><span class="locale-copy locale-copy--en">Opportunities feed</span></span><h2><span class="locale-copy locale-copy--ru">Найдите следующий шаг.</span><span class="locale-copy locale-copy--ro">Găsiți următorul pas.</span><span class="locale-copy locale-copy--en">Find your next step.</span></h2></div>
            <label class="filter-toggle"><input type="checkbox" data-opportunity-filter checked><span><span class="locale-copy locale-copy--ru">Показывать только актуальные</span><span class="locale-copy locale-copy--ro">Afișați doar oportunitățile actuale</span><span class="locale-copy locale-copy--en">Show current only</span></span></label>
        </div>
        <div class="opportunity-feed">
            <article class="page-opportunity-card" data-opportunity-card data-status="current">
                <div class="page-opportunity-card__media">@include('partials.responsive-image', ['name' => 'energy-project', 'alt' => '', 'loading' => 'lazy'])<span class="opportunity-tag opportunity-tag--grant"><span class="locale-copy locale-copy--ru">ГРАНТ</span><span class="locale-copy locale-copy--ro">GRANT</span><span class="locale-copy locale-copy--en">GRANT</span></span></div>
                <div class="page-opportunity-card__body"><h3><span class="locale-copy locale-copy--ru">Поддержка проектов по энергоэффективности</span><span class="locale-copy locale-copy--ro">Sprijin pentru proiecte de eficiență energetică</span><span class="locale-copy locale-copy--en">Support for energy efficiency projects</span></h3><p><span class="locale-copy locale-copy--ru">Placeholder для актуального грантового предложения и его условий.</span><span class="locale-copy locale-copy--ro">Placeholder pentru o oportunitate de grant și condițiile sale.</span><span class="locale-copy locale-copy--en">A placeholder for a current grant opportunity and its terms.</span></p><div class="page-opportunity-card__footer"><span class="page-opportunity-card__deadline"><span class="locale-copy locale-copy--ru">Подать заявку до [дата]</span><span class="locale-copy locale-copy--ro">Depuneți cererea până la [data]</span><span class="locale-copy locale-copy--en">Apply by [date]</span></span><a class="card-link" href="#"><span class="locale-copy locale-copy--ru">Подробнее</span><span class="locale-copy locale-copy--ro">Detalii</span><span class="locale-copy locale-copy--en">Details</span> <span aria-hidden="true">→</span></a></div></div>
            </article>
            <article class="page-opportunity-card" data-opportunity-card data-status="current">
                <div class="page-opportunity-card__media">@include('partials.responsive-image', ['name' => 'infrastructure-beta', 'alt' => '', 'loading' => 'lazy'])<span class="opportunity-tag opportunity-tag--training"><span class="locale-copy locale-copy--ru">ОБУЧЕНИЕ</span><span class="locale-copy locale-copy--ro">INSTRUIRE</span><span class="locale-copy locale-copy--en">TRAINING</span></span></div>
                <div class="page-opportunity-card__body"><h3><span class="locale-copy locale-copy--ru">Практический курс для специалистов</span><span class="locale-copy locale-copy--ro">Curs practic pentru specialiști</span><span class="locale-copy locale-copy--en">Practical course for specialists</span></h3><p><span class="locale-copy locale-copy--ru">Placeholder для будущего курса с программой, датами и условиями участия.</span><span class="locale-copy locale-copy--ro">Placeholder pentru un curs cu program, date și condiții de participare.</span><span class="locale-copy locale-copy--en">A placeholder for a course with programme, dates and participation terms.</span></p><div class="page-opportunity-card__footer"><span class="page-opportunity-card__deadline"><span class="locale-copy locale-copy--ru">Подать заявку до [дата]</span><span class="locale-copy locale-copy--ro">Depuneți cererea până la [data]</span><span class="locale-copy locale-copy--en">Apply by [date]</span></span><a class="card-link" href="#"><span class="locale-copy locale-copy--ru">Подробнее</span><span class="locale-copy locale-copy--ro">Detalii</span><span class="locale-copy locale-copy--en">Details</span> <span aria-hidden="true">→</span></a></div></div>
            </article>
            <article class="page-opportunity-card page-opportunity-card--closed" data-opportunity-card data-status="closed">
                <div class="page-opportunity-card__media">@include('partials.responsive-image', ['name' => 'energy-infrastructure', 'alt' => '', 'loading' => 'lazy'])<span class="opportunity-tag opportunity-tag--contest"><span class="locale-copy locale-copy--ru">КОНКУРС</span><span class="locale-copy locale-copy--ro">CONCURS</span><span class="locale-copy locale-copy--en">CONTEST</span></span></div>
                <div class="page-opportunity-card__body"><h3><span class="locale-copy locale-copy--ru">Идеи для рационального использования энергии</span><span class="locale-copy locale-copy--ro">Idei pentru utilizarea rațională a energiei</span><span class="locale-copy locale-copy--en">Ideas for rational energy use</span></h3><p><span class="locale-copy locale-copy--ru">Placeholder для завершённого конкурса и его итогов.</span><span class="locale-copy locale-copy--ro">Placeholder pentru un concurs finalizat și rezultatele sale.</span><span class="locale-copy locale-copy--en">A placeholder for a completed contest and its results.</span></p><div class="page-opportunity-card__footer"><span class="page-opportunity-card__deadline"><span class="locale-copy locale-copy--ru">Приём завершён</span><span class="locale-copy locale-copy--ro">Înscrierile s-au încheiat</span><span class="locale-copy locale-copy--en">Applications closed</span></span><a class="card-link" href="#"><span class="locale-copy locale-copy--ru">Подробнее</span><span class="locale-copy locale-copy--ro">Detalii</span><span class="locale-copy locale-copy--en">Details</span> <span aria-hidden="true">→</span></a></div></div>
            </article>
        </div>
    </div>
</section>
@endsection
